### PR TITLE
Set language dialect if available

### PR DESCRIPTION
**Pull request by shuber2**
Do not set spelllang to 'en' for 'en_US' in guesslang_langs, i.e., also
pass the language dialect to spelllang.

### CODE REVIEW

**Comment by Konfekt** [comment]
Thank you, but if I recall correctly the dialect was chopped off for a reason: Aspell may very well accept a dialect such as `en-wo_accents`, but Vim not so. One would needs an additional check if this dialect is available in Vim, and if not, use the `spelllang` without dialect.

**Comment by shuber2** [comment]
Hm, but is it a good way to change the language "en-wo_accents", which was explicitly configured as such, to "en" in order to hide a faulty configuration?
If the plugin does not try to be smart on "fixing" the language then vim shows either an error or asks to user whether it should download the spl file, which will then fail. Isn't it?

**Comment by Konfekt** [comment]
The configuration might not faulty, it is just that `aspell` could know different dialects than `vim`. But one can try to keep the accents, and suppress them only if Vim would show an error. Or, if that's too complicated, simply silence any possible error messages by `silent! ...`.

**Comment by shuber2** [comment]
Maybe I am missing a point here, so let me summarize my view on this matter:

1. The user configures a list of potential values for vim's spelllang in the variable g:guesslang_langs.
2. The plugin takes each value, makes an aspell-based test, and eventually picks one for spelllang.

So it is clearly a prerequisite by design that the values in g:guesslang_langs are valid values for spelllang. If the user adds "en-wo_accents" in g:guesslang_langs then step (2) may accept it and set spelllang to it. Then vim asks the user to download the language, which then fails as it is not available.

So what should be the responsibility of vim-DetectSpellLang here? Nothing: It should allow the download mechanism of vim to report to the user that this language is not available. More important, however, it should never change the values in g:guesslang_langs, like "en_US" to "en", which causes vim to falsely mark "virtualization" wrong.

**Comment by Konfekt** [comment]
`:help guesslang-config` says that

> - The language is detected in-between those listed in the variable
  `g:guesslang_langs`. It is *empty* by default and has to be set by the user
  among those listed in `aspell dicts`!

But I see that it is preferable to use the intended accent.

The latest commit now considers the dialect but,hopefully, silences any warnings when setting a dialect Vim does not know about.

**Comment by Konfekt** [comment]
This was apparently solved by the last commit, but now there are some dialects that `aspell` knows about, for example `fr_fr`, but Vim not and setting it to such an unavailable dialect triggers a warning. 

Do you perhaps have an idea how to check if a dialect is available in Vim?

**Comment by Konfekt** [comment]
This will be discussed in https://github.com/Konfekt/vim-DetectSpellLang/issues/4

**Pull request closed without merging**
